### ISSUE TITLE
[Mini Stone] model not visible

### ISSUE THREAD

**Issue by NosferatuJoe** [ManifestManah/Content-Package-Master-Collection#3]
I switched myself to this race and activated thirdperson to view my model but it's invisible or not present. To make sure it wasn't due to the buggy thirdperson mode, I gave a bot the same race and switched back to firstperson mode, unfortunately the issue persisted. So I'm pretty sure the model path is wrong or the model doesn't exist.

**Comment by ManifestManah** [comment]
I do not believe this to be the case.
The model used for this race is a very small model, and most likely almost invisible due to the size of the model being so tiny, so unless you are really looking for this then you probably will not notice the model. I personally do not like this type of race, but after having had multiple people ask me on numerous occassions to re-create these races over the years, I have went ahead and done so. :-)
