### ISSUE TITLE
[Mini Carrot] model not visible

### ISSUE THREAD

**Issue by NosferatuJoe** [ManifestManah/Content-Package-Master-Collection#4]
Same issue as [Mini Stone], renders you invisible for some reason. Tried applying another model like spiderman and that works fine. Not sure what the issue here is.

**Comment by ManifestManah** [comment]
I do not believe this to be the case.
The model used for this race is a very small model, and most likely almost invisible due to the size of the model being so tiny, so unless you are really looking for this then you probably will not notice the model. I personally do not like this type of race, but after having had multiple people ask me on numerous occassions to re-create these races over the years, I have went ahead and done so. :-)
